spring.datasource.url=jdbc:postgresql://localhost:5432/clientesdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false

# Esta propiedad controla si flyway está habilitado o no
spring.flyway.enabled=false
